// src/lib/pdfUtils.ts
import PDFDocument from "pdfkit";

export function generatePatientPDF(data: any): PDFKit.PDFDocument {
  const doc = new PDFDocument({ margin: 50 });

  doc.fontSize(20).text("SmartBridge Patient Summary", { align: "center" });
  doc.moveDown();

  doc.fontSize(12);
  doc.text(`Name: ${data?.name ?? "Unknown"}`);
  doc.text(`Age: ${data?.age ?? "Unknown"}`);
  doc.text(`ID Number: ${data?.idNumber ?? "Unknown"}`);
  doc.text(`Diagnosis: ${data?.diagnosis ?? "N/A"}`);

  doc.moveDown();
  doc.text("Generated by SmartBridge 2.0", { align: "center" });

  doc.end();
  return doc;
}

export function generateMotivationalLetterPDF(
  data: any
): PDFKit.PDFDocument {
  const doc = new PDFDocument({ margin: 50 });

  doc.fontSize(22).text("Motivational Letter", { align: "center" });
  doc.moveDown();

  doc.fontSize(12);
  doc.text(`Patient: ${data?.name ?? "Unknown"}`);
  doc.text(`Age: ${data?.age ?? "Unknown"}`);
  doc.text(`Diagnosis: ${data?.diagnosis ?? "N/A"}`);
  doc.moveDown();

  doc.fontSize(14).text("Letter:", { underline: true });
  doc.moveDown();

  doc.fontSize(12).text(data?.letter ?? "No letter content.", {
    align: "left",
  });

  doc.moveDown();
  doc.text("Generated by SmartBridge 2.0", { align: "center" });

  doc.end();
  return doc;
}
